### ISSUE TITLE
#9: Improve styling

### ISSUE THREAD

**Issue by StephMode** [StephMode/recap-project-4-theme-creator#14]
# Outline

While the design and UI have improved over the course of several refactoring efforts, the app as a whole still looks too default and needs polish.

This is how I can make the app more appealing and unique:
- implement a custom font (favorite: https://fonts.google.com/specimen/Quicksand?preview.text=color)
- implement icons using ReactIcons
- style the buttons
- style the ThemeManager
- change bcg of the app to a tone of black for the moment to make it more visually striking
- add some stylish explanation texts
- add hover effects to the color cards

# Description

## The look I am aiming for:

<img width="405" alt="Image" src="https://github.com/user-attachments/assets/396ddbb4-ed8e-4bc2-858f-516a253c03bb" />

![Image](https://github.com/user-attachments/assets/145697d1-cfd7-4f76-b7d1-08bc2c759eb8)

# Tasks

- [x] Create refactor branch
- [x] Install ReactIcons
- [x] Implement font
- [x] change bcg of app to dark color
- [x] Apply icons to `Button`
- [x] Apply icons to `ThemeManager`
- [x] Adjust layout of App
- [x] Add hover effects on ColorCard
- [x] implement toggle button for add color form
- [x] style the theme manager, the dropdown in particular
- [x] style the "no colors" message
- [x] add header
- [x] add footer

**Comment by StephMode** [comment]
Some inspo for overall design:

https://color.adobe.com/
like the idea of framing the color themes with images that convey the mood of the individual theme

https://colormagic.app/
closest to my current design, but refined

https://palettemaker.com/app
live preview on a website template was also already an idea I had, this is how it could look like

**Comment by StephMode** [comment]
Thoughts on styling structure:

- get rid of the many css files
- Consider implementing styledcomponents

**Comment by StephMode** [comment]
> Ideas:
> 
>     * wrap the Color elements inside flexbox
> 
>     * swap emojis for icons
> 
>     * improve line alignment within Color Card
> 
>     * desgin for mobile viewport definitely needs some optimization

These ideas are outdated.
I've already tackled all of this in earlier refactor PRs.
