### ISSUE TITLE
#10 Refactor button elements in several components

### ISSUE THREAD

**Issue by StephMode** [StephMode/recap-project-4-theme-creator#15]
# Context

I'm still working with `<button>` jsx elements in several components.
This will make it more difficult to style all the buttons once I implement styled components.

Therefore, a dedicated component `Button` is needed.
It shall be concerned with holding the styling and the text-content (to be preplaced by icons further down the line).

# Acceptance Critera

- There's a `Button` component.
- The `Button` component is repsonsible for styling all the buttons and giving them context appropriate content/icons
- The styling for the buttons is centralized in one `.css` file.

# Tasks

- [x] Develop the `Button` component so that it's concerned with styling the button text
- [x] Consolidate all styling used for the button elements in one `.css`
- [x] Refactor all `<button>` elements in the components
- [ ] #34
- [x] Implement error handling in newly developed component to improve type safety

**Comment by StephMode** [comment]
This is the code for a `ColorButton` component I've started working on as I developed issue 4 #5 Edit Color.
I've decided to set it aside because it was not in the scope of the implementation.
While working on #21 jsx and css clean up I decided to remove it from the code base altogether and keep it here, because the context is appropriate:  


```JS
export default function ColorButton() {
  return <button>Lalala</button>;
}

export default function ColorButton() {
  const [showConfirm, setShowConfirm] = useState(false);
  const [showEdit, setShowEdit] = useState(false);
  const [showDelete, setShowDelete] = useState(false);

  function handleDeleteConfirm() {
    // onDeleteColor(cancelButtonStatus); // this only displays clicked-status of delete btn
    onDeleteColor(color.id); // this is what we will need in order to pass ID of clicked color
  }

  function handleDeleteClick() {
    setShowConfirm(true);
  }

  function cancelDelete() {
    setShowConfirm(false);
  }

  function handleEditClick() {
    setShowEdit(true);
    setShowDelete(false);
  }

  function cancelEdit() {
    setShowEdit(false);
  }

  return (
    <div className="color-card--button-container">
      {showDelete === true ? <button>lalala</button> : ""}

      {/* ternary op for Cancel Button UI */}

      {!showConfirm ? (
        <button className="color-card--button" onClick={handleDeleteClick}>
          🗑️ Delete
        </button>
      ) : (
        <div className="buttons-container--confirm-message">
          <p>Really delete?</p>
          <button className="color-card--button" onClick={cancelDelete}>
            ❌ Cancel
          </button>
          <button className="color-card--button" onClick={handleDeleteConfirm}>
            🗑️ Delete
          </button>
        </div>
      )}

      {/* ternary op for Edit Button UI */}
      {!showEdit ? (
        <button className="color-card--button" onClick={handleEditClick}>
          🖍️ Edit
        </button>
      ) : (
        <div>
          <ColorEditor></ColorEditor>
          <button className="color-card--button" onClick={cancelEdit}>
            ❌ Cancel
          </button>
        </div>
      )}
    </div>
  );
}


```

**Comment by StephMode** [comment]
# Sidenote

There are several "sucess message" elements related to buttons througout the app. It might make sense to turn these instances into one component as well while I'm working on the buttons anyway. This would make it even simpler to work on the styling in a centralized non-DRY manner later on.

**Comment by StephMode** [comment]
Classes and css files I need to consolidate:

`className="color-card--button"`
