### ISSUE TITLE
#15 css & jsx standardization and cleanup

### ISSUE THREAD

**Issue by StephMode** [StephMode/recap-project-4-theme-creator#21]
**Overview**

There are inconsistencies regarding naming of the files:

![Bildschirmfoto 2024-11-02 um 15 22 08](https://github.com/user-attachments/assets/02c05d2e-2a59-47b9-ab8a-6fd136a64dda)

There are empty `css` files which need to be deleted, such as `ColorEditor.css`.

There are inconsistencies in the css. 
🟢 Sometimes I use class selectors, like in `ColorForm.css`
🔴 Sometimes I use type selectors, like in `ContrastChecker.css`
=> I should use class selectors everywhere.

Several `.jsx` files contain unneccesary logs, code that's commented-out and not needed anymore and comments. I should:
- delete logs & code that's commented-out and not needed
- move comments on my approach elsewhere out of the `jsx files`

**Tasks**

- [x] Standardize naming of `Component.jsx`
  - [x] Change name for `ContrastChecker using `PascalCase`
- [x] Delete empty `.css` files
- [x] clean up and standardize `css` files and apply class selectors whenever possible
- [x] clean up `jsx` files deleting comments, clogs, commented-out code

**Comment by StephMode** [comment]
**Pivot on** Standardize naming of Component.jsx

There is no fixed spec for naming `.jsx` files as React is unopinionated on this. See: https://stackoverflow.com/questions/43973199/file-naming-conventions-in-reactjs.

I'll stick with `PascalCase` for naming of my `Component.jsx` files. Instead, I'll rename the `ContrastChecker`file.

**Comment by StephMode** [comment]
> **Pivot on** Standardize naming of Component.jsx
> 
> There is no fixed spec for naming `.jsx` files as React is unopinionated on this. See: https://stackoverflow.com/questions/43973199/file-naming-conventions-in-reactjs.
> 
> I'll stick with `PascalCase` for naming of my `Component.jsx` files. Instead, I'll rename the `ContrastChecker`file.

Accidentially commited it to `main`. Will open `refactor` branch now.

**Comment by StephMode** [comment]
decided to leave the following comps as they are for now:
**CopyTo**: comments are hints for improvements and refactoring. They are useful and shall remain.
**ColorInput**: Have to work on it for a bug fix anyway, so leave it as it is for now
